### PR TITLE
Change single quotes to double quotes

### PR DESCRIPTION
**Pull request by ederzadravec**
## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator

### CODE REVIEW

**Comment by dblachut-adb** [comment]
How is this not merged yet? :)

**Comment by Naturalclar** [comment]
For some reason I'm not able to checkout from this PR, so I created a new PR to fix the issue #262

**Comment by Naturalclar** [comment]
Merged in #262

**Comment by dblachut-adb** [comment]
image

**Pull request closed without merging**
