### PR TITLE
feat(iOS): Callback for volume changed events

### PR DESCRIPTION
**Pull request by tejachundru**
Enabling the **Voice.onSpeechVolumeChanged(event)** for iOS,
 The Audio level is normalized to scale of 0-10, similar to the android functionality.

### CODE REVIEW

**Comment by emilioheinz** [comment]
Why does that still not approved? That is a important feature for the lib!!

+1

**Comment by emilioheinz** [comment]
@sibelius

**Comment by safaiyeh** [comment]
hi @tejachundru could you add an example in the `example` project so I could easily test this?
Thanks!

**Comment by safaiyeh** [comment]
Hopefully we can land this, it has been years LOL

**Comment by tejachundru** [comment]
@safaiyeh You can Just checkout to the https://github.com/tejachundru/react-native-voice
and run the Example, 


[Supported Events](https://github.com/react-native-community/voice#events)

for IOS **Voice.onSpeechVolumeChanged(event)**  now gives you the value.

Please let me know if there is anything, I can add.

**Comment by safaiyeh** [comment]
@Naturalclar what do you think about merging this?

**Comment by Naturalclar** [comment]
@safaiyeh sounds good :+1:

**Pull request merged**
