### PR TITLE
Make content of buildscript optional

### PR DESCRIPTION
**Pull request by dmitrybolt**
# Summary
Fix gradle build error where it can't find specified version of gradle.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist
- [X] I have tested this on a device and a simulator

### CODE REVIEW

**Comment by safaiyeh** [comment]
hi @dmitrybolt thanks for the PR. Can you explain your motivation for this more?

**Comment by dmitrybolt** [comment]
Hi @safaiyeh! Gradle plugin only required when opening the project stand-alone. Error occurs because version of gradle specified in build.gradle file cannot be found by android studio (clean install, latest version).

**Comment by dmitrybolt** [comment]
@safaiyeh https://github.com/facebook/react-native/pull/25569#issuecomment-532504277

**Comment by safaiyeh** [comment]
Thanks for the reference! I'll land this.

**Pull request merged**
